{{- if .Values.istio.enabled -}}
{{- $fullName := include "simple-server.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "simple-server.labels" . | nindent 4 }}
  {{- with .Values.istio.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    istio: "ingressgateway"
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.istio.hosts }}
        - {{ .host | quote }}
        {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "simple-server.labels" . | nindent 4 }}
  {{- with .Values.istio.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
  {{- range .Values.istio.hosts }}
  - {{ .host | quote }}
  {{- end }}
  gateways:
  - {{ $fullName }}
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: {{ include "simple-server.fullname" . }}
{{- end }}